### ISSUE TITLE
Checklist for publishing to production

### ISSUE THREAD

**Issue by maximekabel** [CosmosTUe/Cosmos#171]
- [x] Update nginx config
- [x] Remove old crispy-bootstrap5 package
- [x] Backup userdata
- [x] Update the `secrets.json`
- [x] Remove broken djangocms migration after publishing
